name: 自动同步代码到 Gitee

on:
  push:
    branches: 
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1

    - name: 自动同步代码到 Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github.com/luckykeeper
        dst: gitee.com/luckykeeper
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        static_list: "LOVE69_renpy_remaster"
        debug: true
        force_update: true