name: 自动同步代码到 Gitee

on:
  push:
  pull_request_target:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source codes
      uses: actions/checkout@v1

    - name: 自动同步代码到 Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/luckykeeper
        dst: gitee/luckykeeper
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        white_list: "LOVE69_renpy_remaster"
        static_list: "LOVE69_renpy_remaster"
        cache_path: /github/workspace/hub-mirror-cache
        debug: true
        force_update: true